### PR TITLE
Workaround to silence module attribute warning

### PR DESCRIPTION
**Pull request by vic**

### CODE REVIEW

**Comment by arjan** [comment]
While there is nothing wrong with this PR I'm a bit hesistant to merge it; because I don't like the syntax and dont really want to promote it :-S

In a previous approach (vsn 0.1.0) I generated decorator macros for each decorator. But they did not look so nice (no @ at the beginning of the decorator). 

However they had  the advantage of compile-type error checking; you get an error when trying a decorator that doesnt exist (as opposed to the @ syntax)

So I have been pondering using the `_` symbol instead of `@` as the decorator; what do you think of this syntax?

``` elixir
_annotated()
def some_function(foo) do
  # ...
```

**Comment by arjan** [comment]
Another option is to let the decorator implementer choose between syntaxes, or even have a per project setting; but that will lead to even more confusion.

**Comment by vic** [comment]
I'd prefer the `@` syntax, as it's more familiar to decorators in others languages (thinking of python and java). The downside is the elixir compiler checks for _module-attribute-look-alikes_ to be used and thus the `_ = @deco` hack.

Regarding the `_` one, I'd prefer to live it out, and just use the decorator name, the downside to both is that it's not clear the _function call_ would actually be decorating a function:

```
annotated()  # not really clear to the eyes this will be affecting the following function def.

def some_function(foo) do
  ...
```

How about always using a `@deco`, I guess this would also simplify the code, maybe the custom `@` macro and the `at_override` could be removed with this. Can provide an alternative branch with this if you want.

```
@deco annotated()
def some_function(foo) do
```

Not as pretty as `@annotated()` but it'd be certainly more _elixirish_.

**Comment by arjan** [comment]
I agree with you. `@deco` is more explicit. It also reminds me of the [Erlang version](https://github.com/chrisavl/erlang_decorators/tree/master) of this project which uses the same syntax.

Let's just call it `@decorator`, to be even more explicit.

Do you think this also would work for decorators with arguments?

Would be nice if this could be implemented using `defmacro @decorated(..)` but I don't think that's valid Elixir syntax. Overriding `Kernel.@` still feels a bit like a hack :) Do you have time to work on this?

**Comment by arjan** [comment]
Update: I'm having a go at this myself right now :)

**Comment by arjan** [comment]
Thanks for your suggestion; it works pretty well. I have released 0.3.0 with the changed `@decorator` syntax.

**Comment by arjan** [comment]
Hmm looking at the [Erlang counterpart](https://github.com/chrisavl/erlang_decorators/blob/master/test/decorator_test.erl), I see they use the `@decorate` annotation. That's maybe a bit more clear, given that's an imperative, instead of a noun. What do you think?

**Pull request closed without merging**
