### PR TITLE
Empty body decorate

### PR DESCRIPTION
**Pull request by ludwikbukowski**
This PR will work once those will be merged: 
- https://github.com/arjan/decorator/pull/20
- https://github.com/arjan/decorator/pull/22

IT resolves the issue from: https://github.com/arjan/decorator/issues/18

### CODE REVIEW

**Comment by arjan** [comment]
I merged #20 and #22, thanks for that. Is this PR still relevant?
I've pushed out release 1.2.4 as well.

**Comment by arjan** [comment]
Oh wait I see this is a different issue, can you resolve the conflicts?

**Comment by ludwikbukowski** [comment]
@arjan There is some issue related to old Elixir version 1.3

**Comment by arjan** [comment]
Strange, does not seem too bad to me. I'm open for increasing the minimum Elixir version for next release, can you try that? e.g. to 1.5

**Comment by ludwikbukowski** [comment]
Im just going to create a new PR because this PR was based on my already customised branch and commits history is getting messy

**Comment by ludwikbukowski** [comment]
https://github.com/arjan/decorator/pull/27

**Pull request closed without merging**
